### PR TITLE
feat: Create degree validation modal

### PR DESCRIPTION
**Pull request by jasonappah**
## Overview

List the GitHub issues containing the issues relevant to this pull request.

[For example, "Resolves #1, closes #2, fixes #3", etc.]

Describe your changes here at a high level, describing how this PR fits into the
rest of the project.

This PR integrates the [degree validation API](https://github.com/ez314/Degree-Validator) with the plan editor with a modal.

image
image

## What Changed

Go more into detail about key files that were modified and why they were
updated. Do not list every file that was modified; only note the ones most
relevant to this feature or bug fix.

I modified the toolbar to include a button to display the modal, and created a component which handles data fetching from the validation API.

## Other Notes

Before this gets merged, the `NEXT_PUBLIC_VALIDATION_SERVER` environment variable needs to be set in Vercel, pointing to wherever the API will be hosted.

### CODE REVIEW

**Comment by ez314** [comment]
Looks awesome! Just wondering, did you override CS 3305 with 6 credit hours?

**Comment by jasonappah** [comment]
I didn't add any overrides here, but I just noticed that CS 3305 is in the test degree plan twice.

**Review by ZzRanger — COMMENTED** [review]
Great job! Just a couple of nitpicks but otherwise looks good to me!

**Review by ZzRanger — APPROVED** [review]
LGTM!

**Pull request merged**
