### PR TITLE
Np 124 - getting rid of mui autocomplete

### PR DESCRIPTION
**Pull request by NoWhere-2-Go**
Used react-select which does not actively support options that are just simple strings so I had to convert the list of majors into `{ label: element, value: element }` format

### CODE REVIEW

**Comment by akevinge** [comment]
Wasn't sure if this was ready to be reviewed, but could you style it as seen in the Figma:
https://www.figma.com/file/nW5wBYFetauCmIdt9e5BtA/Nebula-Planner?type=design&node-id=607-4948&mode=dev?

Also, the integration tests rely on the MUI component to select a major during plan creation. We should fix that to work with the new select if possible!

**Review by akevinge — CHANGES_REQUESTED** [review]
Wasn't sure if this was ready to be reviewed, but could you style it as seen in the Figma:
https://www.figma.com/file/nW5wBYFetauCmIdt9e5BtA/Nebula-Planner?type=design&node-id=607-4948&mode=dev?

Also, the integration tests rely on the MUI component to select a major during plan creation. We should fix that to work with the new select if possible!

**Comment by akevinge** [comment]
Lmk if you need help figuring out integration test stuff. We run them locally via `npm run cypress:open`, the validator also needs to be running before you run the test.

**Comment by kamui-fin** [comment]
Stale and #728 resuming progress.

**Pull request closed without merging**
