### PR TITLE
fix: rename route test-validate => validate

### PR DESCRIPTION
**Pull request by akevinge**

### CODE REVIEW

**Review by cubetastic33 — CHANGES_REQUESTED** [review]
The usages aren't updated, are they?

**Comment by akevinge** [comment]
> The usages aren't updated, are they?

I thought the only usage was in `validator.ts` :thinking: might have missed one?

**Comment by cubetastic33** [comment]
> > The usages aren't updated, are they?
> 
> I thought the only usage was in `validator.ts` 🤔 might have missed one?

Oh my bad the other usage was in the dead code

**Review by cubetastic33 — APPROVED** [review]
lgtm

**Pull request merged**
